---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      name: php-apache
  template:
    metadata:
      name: pod-php
      labels:
        name: php-apache
    spec:
      containers:
        - name: php-apache
          image: intelliqit/mynew
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    name: php-apache
spec:
  ports:
    - port: 80
  selector:
    name: php-apache
...

