---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: httpd-rc
  labels:
    type: webserver
    author: naveen
spec:
  replicas: 3
  template:
    metadata:
      name: httpd-pod
      labels:
        author: nag  
    spec:
      containers:
        - name: myhttpd 
          image: httpd
          ports:
           - containerPort: 80
             hostPort: 8080
...            
