---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    type: webserver
spec:
  
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: httpd-pod
      labels:
        type: webserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
      tolerations:
        - key: slave1
          operator: Equal
          value: intelliqit1
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/hostname: gke-cluster-1-default-pool-451e0d94-3x4r 
...

