--
apiVersion: v1
kind: Namespace
metadata:
  name: dev-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-pod
  namespace: dev-ns
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-rolebinding
  namespace: dev-ns
subjects:
  - kind: User
    name: naveen
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-pod
  apiGroup: rbac.authorization.k8s.io
  
