---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: resultapp-deployment
 labels: 
  name: result-app
  author: naveen 
spec: 
  replicas: 2 
  selector:
    matchLabels: 
      name: result-app
  template: 
    metadata: 
      name: resultapp-pod 
      labels:
        name: result-app
    spec: 
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result 
...

