---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: votingapp-deployment
  labels: 
    name: voting-app
    author: naveen
spec: 
  replicas: 2
  selector: 
    matchLabels:
      name: voting-app
  template: 
    metadata:
      name: votingapp-pod
      labels: 
        name: voting-app
    spec: 
      containers: 
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
...       
